/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KontoRouteRouteImport } from './routes/konto/route'
import { Route as CategoryRouteRouteImport } from './routes/category/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryIndexRouteImport } from './routes/category/index'
import { Route as AnnonceIndexRouteImport } from './routes/annonce/index'
import { Route as CategoryCategoryRouteImport } from './routes/category/$category'
import { Route as KontoProfileIndexRouteImport } from './routes/konto/profile/index'
import { Route as KontoAnnoncerIndexRouteImport } from './routes/konto/annoncer/index'
import { Route as authSignupIndexRouteImport } from './routes/(auth)/signup/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as CategoryProductProductRouteImport } from './routes/category/product/$product'

const KontoRouteRoute = KontoRouteRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRouteRoute = CategoryRouteRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoryRouteRoute,
} as any)
const AnnonceIndexRoute = AnnonceIndexRouteImport.update({
  id: '/annonce/',
  path: '/annonce/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => CategoryRouteRoute,
} as any)
const KontoProfileIndexRoute = KontoProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => KontoRouteRoute,
} as any)
const KontoAnnoncerIndexRoute = KontoAnnoncerIndexRouteImport.update({
  id: '/annoncer/',
  path: '/annoncer/',
  getParentRoute: () => KontoRouteRoute,
} as any)
const authSignupIndexRoute = authSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => authRouteRoute,
} as any)
const CategoryProductProductRoute = CategoryProductProductRouteImport.update({
  id: '/product/$product',
  path: '/product/$product',
  getParentRoute: () => CategoryRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/category': typeof CategoryRouteRouteWithChildren
  '/konto': typeof KontoRouteRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/annonce': typeof AnnonceIndexRoute
  '/category/': typeof CategoryIndexRoute
  '/category/product/$product': typeof CategoryProductProductRoute
  '/login': typeof authLoginIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/konto/annoncer': typeof KontoAnnoncerIndexRoute
  '/konto/profile': typeof KontoProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/konto': typeof KontoRouteRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/annonce': typeof AnnonceIndexRoute
  '/category': typeof CategoryIndexRoute
  '/category/product/$product': typeof CategoryProductProductRoute
  '/login': typeof authLoginIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/konto/annoncer': typeof KontoAnnoncerIndexRoute
  '/konto/profile': typeof KontoProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/category': typeof CategoryRouteRouteWithChildren
  '/konto': typeof KontoRouteRouteWithChildren
  '/category/$category': typeof CategoryCategoryRoute
  '/annonce/': typeof AnnonceIndexRoute
  '/category/': typeof CategoryIndexRoute
  '/category/product/$product': typeof CategoryProductProductRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/signup/': typeof authSignupIndexRoute
  '/konto/annoncer/': typeof KontoAnnoncerIndexRoute
  '/konto/profile/': typeof KontoProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/category'
    | '/konto'
    | '/category/$category'
    | '/annonce'
    | '/category/'
    | '/category/product/$product'
    | '/login'
    | '/signup'
    | '/konto/annoncer'
    | '/konto/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/konto'
    | '/category/$category'
    | '/annonce'
    | '/category'
    | '/category/product/$product'
    | '/login'
    | '/signup'
    | '/konto/annoncer'
    | '/konto/profile'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/category'
    | '/konto'
    | '/category/$category'
    | '/annonce/'
    | '/category/'
    | '/category/product/$product'
    | '/(auth)/login/'
    | '/(auth)/signup/'
    | '/konto/annoncer/'
    | '/konto/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  CategoryRouteRoute: typeof CategoryRouteRouteWithChildren
  KontoRouteRoute: typeof KontoRouteRouteWithChildren
  AnnonceIndexRoute: typeof AnnonceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/': {
      id: '/category/'
      path: '/'
      fullPath: '/category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof CategoryRouteRoute
    }
    '/annonce/': {
      id: '/annonce/'
      path: '/annonce'
      fullPath: '/annonce'
      preLoaderRoute: typeof AnnonceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof CategoryRouteRoute
    }
    '/konto/profile/': {
      id: '/konto/profile/'
      path: '/profile'
      fullPath: '/konto/profile'
      preLoaderRoute: typeof KontoProfileIndexRouteImport
      parentRoute: typeof KontoRouteRoute
    }
    '/konto/annoncer/': {
      id: '/konto/annoncer/'
      path: '/annoncer'
      fullPath: '/konto/annoncer'
      preLoaderRoute: typeof KontoAnnoncerIndexRouteImport
      parentRoute: typeof KontoRouteRoute
    }
    '/(auth)/signup/': {
      id: '/(auth)/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/category/product/$product': {
      id: '/category/product/$product'
      path: '/product/$product'
      fullPath: '/category/product/$product'
      preLoaderRoute: typeof CategoryProductProductRouteImport
      parentRoute: typeof CategoryRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
  authSignupIndexRoute: typeof authSignupIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
  authSignupIndexRoute: authSignupIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface CategoryRouteRouteChildren {
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
  CategoryProductProductRoute: typeof CategoryProductProductRoute
}

const CategoryRouteRouteChildren: CategoryRouteRouteChildren = {
  CategoryCategoryRoute: CategoryCategoryRoute,
  CategoryIndexRoute: CategoryIndexRoute,
  CategoryProductProductRoute: CategoryProductProductRoute,
}

const CategoryRouteRouteWithChildren = CategoryRouteRoute._addFileChildren(
  CategoryRouteRouteChildren,
)

interface KontoRouteRouteChildren {
  KontoAnnoncerIndexRoute: typeof KontoAnnoncerIndexRoute
  KontoProfileIndexRoute: typeof KontoProfileIndexRoute
}

const KontoRouteRouteChildren: KontoRouteRouteChildren = {
  KontoAnnoncerIndexRoute: KontoAnnoncerIndexRoute,
  KontoProfileIndexRoute: KontoProfileIndexRoute,
}

const KontoRouteRouteWithChildren = KontoRouteRoute._addFileChildren(
  KontoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  CategoryRouteRoute: CategoryRouteRouteWithChildren,
  KontoRouteRoute: KontoRouteRouteWithChildren,
  AnnonceIndexRoute: AnnonceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
